BaseUrl= "http://jcislinsky.github.io/public/"
LanguageCode= "cs-cz"
Title= "Jan Cislinsky"
# paginate = 5
DisqusShortname = "jancislinsky"
Copyright = "All rights reserved – 2016"
canonifyurls = true
theme = "casper"

[[menu.main]]
  name = "Úvodní stránka"
  weight = -120
  identifier = "home"
  url = "/"
  
[params]
  description = "iOS developer ve společnosti Etnetera a.s."
  cover = "images/cover.jpg"
  author = "Jan Cislinsky"
  bio= "iOS developer ve společnosti Etnetera a.s."
  authorlocation = ""
  authorwebsite = ""
  
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-11117746-14"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "jcislinsky"
  twitterName = "jcislinsky"
  # facebookName = ""
  linkedinName = "jcislinsky"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false