BaseUrl= "https://www.jancislinsky.cz/"
LanguageCode= "cs-cz"
Title= "Jan Čislinský"
# paginate = 5
DisqusShortname = "jancislinsky"
Copyright = "© 2018"
canonifyurls = true
theme = "casper"

[[menu.main]]
  name = "Úvodní stránka"
  weight = -120
  identifier = "home"
  url = "/"
  
[params]
  description = "Lead iOS developer ve společnosti Etnetera a.s."

  myApps = "Moje aplikace"

  myApp1Image = "images/app-zvednout-to.png"
  myApp1Name = "Zvednout to?"
  myApp1Url = "http://apple.co/2jsfavB"

  myApp2Image = "images/app-siever.png"
  myApp2Name = "Siever"
  myApp2Url = "https://itunes.apple.com/us/app/siever/id1276667985?ls=1&mt=8"

  cover = "images/cover.jpg"
  author = "Jan Čislinský"
  bio= "Lead iOS developer ve společnosti Etnetera a.s."
  authorlocation = ""
  authorwebsite = ""
  
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-11117746-14"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "jcislinsky"
  twitterName = "jcislinsky"
  # facebookName = ""
  linkedinName = "jcislinsky"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false